INSERT INTO country(id, code, name) VALUES ('1', 'SA','Afrique du Sud');
INSERT INTO country(id, code, name) VALUES ('2', 'DZ', 'Algérie');
INSERT INTO country(id, code, name) VALUES ('3', 'DE', 'Allemagne');
INSERT INTO country(id, code, name) VALUES ('4', 'AE', 'Arabie Saoudite');
INSERT INTO country(id, code, name) VALUES ('5', 'AR', 'Argentine');
INSERT INTO country(id, code, name) VALUES ('6', 'AM', 'Arménie');
INSERT INTO country(id, code, name) VALUES ('7', 'AU', 'Australie');
INSERT INTO country(id, code, name) VALUES ('8', 'AT', 'Autriche');
INSERT INTO country(id, code, name) VALUES ('9', 'BE', 'Belgique');
INSERT INTO country(id, code, name) VALUES ('10', 'BR', 'Brésil');
INSERT INTO country(id, code, name) VALUES ('11', 'CA', 'Canada');
INSERT INTO country(id, code, name) VALUES ('12', 'CN', 'Chine');
INSERT INTO country(id, code, name) VALUES ('13', 'CO', 'Colombie');
INSERT INTO country(id, code, name) VALUES ('14', 'KW', 'Corée du Sud');
INSERT INTO country(id, code, name) VALUES ('15', 'HR', 'Croatie');
INSERT INTO country(id, code, name) VALUES ('16', 'DK', 'Danemark');
INSERT INTO country(id, code, name) VALUES ('17', 'AE', 'Emirats arabe unis');
INSERT INTO country(id, code, name) VALUES ('18', 'ES', 'Espagne');
INSERT INTO country(id, code, name) VALUES ('19', 'US', 'Etats-Unis');
INSERT INTO country(id, code, name) VALUES ('20', 'FR', 'France');
INSERT INTO country(id, code, name) VALUES ('21', 'IN','Inde');
INSERT INTO country(id, code, name) VALUES ('22', 'ID', 'Indonésie');
INSERT INTO country(id, code, name) VALUES ('23', 'IE', 'Irlande');
INSERT INTO country(id, code, name) VALUES ('24', 'IT', 'Italie');
INSERT INTO country(id, code, name) VALUES ('25', 'JP', 'Japon');
INSERT INTO country(id, code, name) VALUES ('26', 'LU', 'Luxembourg');
INSERT INTO country(id, code, name) VALUES ('27', 'MA', 'Maroc');
INSERT INTO country(id, code, name) VALUES ('28', 'MC', 'Monaco');
INSERT INTO country(id, code, name) VALUES ('29', 'NO', 'Norvège');
INSERT INTO country(id, code, name) VALUES ('30', 'QA', 'Qatar');
INSERT INTO country(id, code, name) VALUES ('31', 'GB', 'Royaume-uni');
INSERT INTO country(id, code, name) VALUES ('32', 'SG', 'Singapour');
INSERT INTO country(id, code, name) VALUES ('33', 'SE', 'Suède');
INSERT INTO country(id, code, name) VALUES ('34', 'CH', 'Suisse');
INSERT INTO country(id, code, name) VALUES ('35', 'TZ', 'Taïwan');
INSERT INTO country(id, code, name) VALUES ('36', 'TN', 'Tunisie');