version: "3.8"
networks:
  ecommerce-db-compose:
services:
  ecommerce-springboot:
    image: ecommerce-springboot
    build:
      context: ./server/ecommerce
      dockerfile: shoppingportal.Dockerfile
    ports:
      - 8080:8080
    networks:
      - ecommerce-db-compose
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_USER: ecommerce-user
      POSTGRES_PASSWORD: ecommerce-pwd
      POSTGRES_DB: ecommerce-db
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ecommerce-db-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce-user -d ecommerce-db"]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 5s
  ecommerce-angular:
    image: ecommerce-angular
    build:
      context: ./client/ecommerce-app
      dockerfile: ecommerce-angular.Dockerfile
    ports:
      - 4200:80
    networks:
      - ecommerce-db-compose
    depends_on:
      - ecommerce-springboot
